/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hoppe' at '13/05/14 7:16 PM' with Gradle 1.11
 *
 * @author hoppe, @date 13/05/14 7:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
